
CREATE TABLE "statements"."MessageIdempotentStore"("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,"error" VARCHAR(2000),"messageId" VARCHAR(1000) NOT NULL,CONSTRAINT "MessageIdempotentStore_PK" PRIMARY KEY("id"),CONSTRAINT "MessageIdempotentStore_messageId_UNQ" UNIQUE("messageId"));
ALTER TABLE "statements"."MessageIdempotentStore" ALTER COLUMN "id" RESTART WITH 0;

CREATE INDEX "MessageIdempotentStore_N52" ON "statements"."MessageIdempotentStore"("messageId");
