
CREATE TABLE "statements"."MailStatementProfile"("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,"fileNamePattern" VARCHAR(128) NOT NULL, "fromAddress" VARCHAR(255), "subjectWords" VARCHAR(255) NOT NULL,"folderName" VARCHAR(255) NOT NULL,"readerId" BIGINT NOT NULL, "sourceId" BIGINT NOT NULL, "mailConnectionProfileId" BIGINT NOT NULL,"description" VARCHAR(4000),"name" VARCHAR(40) NOT NULL,"version" TIMESTAMP NOT NULL,CONSTRAINT "MailStatementProfile_PK" PRIMARY KEY("id"),CONSTRAINT "MailStatementProfile_name_UNQ" UNIQUE("name"));
ALTER TABLE "statements"."MailStatementProfile" ALTER COLUMN "id" RESTART WITH 0;

CREATE INDEX "MailStatementProfile_N51" ON "statements"."MailStatementProfile"("sourceId");
CREATE INDEX "MailStatementProfile_N50" ON "statements"."MailStatementProfile"("readerId");
CREATE INDEX "MailStatementProfile_N49" ON "statements"."MailStatementProfile"("mailConnectionProfileId");

ALTER TABLE "statements"."MailStatementProfile" ADD CONSTRAINT "MailStatementProfile_FK3" FOREIGN KEY("mailConnectionProfileId") REFERENCES "statements"."MailConnectionProfile"("id");
ALTER TABLE "statements"."MailStatementProfile" ADD CONSTRAINT "MailStatementProfile_FK2" FOREIGN KEY("readerId") REFERENCES "statements"."StatementReader"("id");
ALTER TABLE "statements"."MailStatementProfile" ADD CONSTRAINT "MailStatementProfile_FK1" FOREIGN KEY("sourceId") REFERENCES "statements"."StatementSource"("id");
