language: java
jdk:
- oraclejdk8

# Build everything in 'script' phase
install: /bin/true

#script:
#- mvn clean install
	- mvn clean install -Dmavenmixin-jettyconsole

cache:
  directories:
  - .autoconf
  - $HOME/.m2

